/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Contract version implemented by this native addon. */
export declare function nativeContractVersion(): number
/**
 * Optimization profile this addon was compiled with: `release` or `debug`.
 * Performance measurements are only meaningful against `release`.
 */
export declare function nativeBuildProfile(): string
export interface HistoryQueryOptions {
  dbPath?: string
  source?: string
  project?: string
  tag?: string
  beforeMs?: number
  limit?: number
}
export interface SearchOptions {
  dbPath?: string
  source?: string
  project?: string
  tag?: string
  beforeMs?: number
  limit?: number
  rawFts?: boolean
}
export interface SessionOptions {
  dbPath?: string
  source?: string
  tag?: string
}
export interface NativeHistoryEntry {
  id: number
  source: string
  sessionId?: string
  project?: string
  prompt: string
  timestampMs: number
}
export interface NativeSessionEvent {
  id: number
  source: string
  sessionId: string
  project?: string
  cwd?: string
  gitBranch?: string
  messageId?: string
  parentId?: string
  tsMs: number
  role: string
  kind: string
  text?: string
  model?: string
  tokenJson?: string
  eventUid: string
}
export interface EventCursor {
  tsMs: number
  id: number
}
export interface EventsPageOptions {
  dbPath?: string
  source?: string
  limit?: number
  after?: EventCursor
}
export interface SessionEventsPage {
  events: Array<NativeSessionEvent>
  nextCursor?: EventCursor
}
export interface SourceCount {
  source: string
  count: number
}
export interface ProjectCount {
  project: string
  count: number
}
export interface NativeStats {
  total: number
  bySource: Array<SourceCount>
  byProject: Array<ProjectCount>
  firstTimestampMs?: number
  lastTimestampMs?: number
}
export interface StatsOptions {
  dbPath?: string
  tag?: string
}
/** Full-text search of indexed history. Never discovers or syncs implicitly. */
export declare function search(query: string, options?: SearchOptions | undefined | null): Promise<Array<NativeHistoryEntry>>
/** Recent indexed history. Never discovers or syncs implicitly. */
export declare function recent(options?: HistoryQueryOptions | undefined | null): Promise<Array<NativeHistoryEntry>>
/** Indexed prompts for one session. Event payloads are separately paginated. */
export declare function getSession(sessionId: string, options?: SessionOptions | undefined | null): Promise<Array<NativeHistoryEntry>>
/** One bounded page of normalized events for a session. */
export declare function getSessionEventsPage(sessionId: string, options?: EventsPageOptions | undefined | null): Promise<SessionEventsPage>
/** Database statistics over already-indexed data. */
export declare function stats(options?: StatsOptions | undefined | null): Promise<NativeStats>
export interface CatalogSession {
  source: string
  sessionId: string
  cwd?: string
  gitBranch?: string
  firstActivityMs?: number
  lastActivityMs?: number
  firstPrompt?: string
  lastAssistantText?: string
  models: Array<string>
  originator?: string
  agentVersion?: string
  repoUrl?: string
  initialCommit?: string
  workspaceRoots: Array<string>
  rawPath?: string
  sourceStamp?: string
  discoveryState: string
  fromCache: boolean
}
export interface CatalogCursor {
  lastActivityMs?: number
  source: string
  sessionId: string
}
export interface ListCatalogOptions {
  dbPath?: string
  sources?: Array<string>
  limit?: number
  beforeMs?: number
  after?: CatalogCursor
}
export interface SessionCatalogPage {
  contractVersion: number
  sessions: Array<CatalogSession>
  nextCursor?: CatalogCursor
}
/** Cache-only indexed catalog query. Missing databases return an empty page. */
export declare function listSessionCatalogPage(options?: ListCatalogOptions | undefined | null): Promise<SessionCatalogPage>
/** Convenience first-page catalog listing with identical cache-only semantics. */
export declare function listSessionCatalog(options?: ListCatalogOptions | undefined | null): Promise<Array<CatalogSession>>
export interface DiscoverOptions {
  dbPath?: string
  sources?: Array<string>
  limit?: number
}
export interface DiscoveryDiagnostic {
  source: string
  locator?: string
  error: string
}
export interface ProviderSummary {
  source: string
  candidates: number
  discovered: number
  skippedUnchanged: number
  failed: boolean
}
export interface DiscoveryCounters {
  candidatesEnumerated: number
  shallowReads: number
  skippedUnchanged: number
  filesOpened: number
  bytesRead: number
}
export interface SourceExemption {
  source: string
  reason: string
}
export interface DiscoverResult {
  contractVersion: number
  sessions: Array<CatalogSession>
  discovered: number
  skippedUnchanged: number
  providers: Array<ProviderSummary>
  exemptSources: Array<SourceExemption>
  diagnostics: Array<DiscoveryDiagnostic>
  counters: DiscoveryCounters
}
/** Explicit bounded provider discovery. It updates only the session catalog. */
export declare function discoverSessions(options?: DiscoverOptions | undefined | null): Promise<DiscoverResult>
export interface SyncOptions {
  dbPath?: string
}
export interface SyncResult {
  databasePath: string
  completed: boolean
}
/** Explicit full ingestion. A read operation never calls this implicitly. */
export declare function sync(options?: SyncOptions | undefined | null): Promise<SyncResult>
/** Backward-compatible internal capture entry point; not used by the SDK. */
export declare function syncLocal(): Promise<void>
export interface SyncPushResult {
  sent: number
  accepted: number
  authenticated: boolean
  syncSkipped: boolean
}
/** Cloud capture hook retained for Agent Relay integration. */
export declare function syncAndPush(): Promise<SyncPushResult>
